### ISSUE TITLE
Taxonomies are invisible for members if discussions with a tag which hidden from visitors

### ISSUE THREAD

**Issue by imshuzai** [flamarkt/taxonomies#5] opened 2022-06-28 05:56 UTC
I installed Taxonomies on my forum. There is a tag on my forum that is hidden from visitors and visible to members. I set the permissions on this tag to allow members to see taxonomies on their own discussion, and allowed edit taxonomies on own discussions .but non-admin members (including mods) still can't see taxonomies on discussions with that tag, whether or not they are their own discussions. They can't edit taxonomies on their own discussion which is with that tag too. The filter works fine, even if taxonomies are not visible.
I tested this on a fresh install Flarum and got the same issue.

Reproduction steps:
1. Create a tag A.
2. Set the tag A to be visible only to members on the permissions page.
3. Start a discussion with tag A and set taxonomies.
4. Login with a non-admin user and view the discussion.

Screenshots:

![86cb88cf65fecb007eb1219fd5e982f.png](https://img3.qq.tc/2022/06/28/86cb88cf65fecb007eb1219fd5e982f.png)
![c9375f3fcd823794fbeff13df06a5f3.png](https://img3.qq.tc/2022/06/28/c9375f3fcd823794fbeff13df06a5f3.png)
![6e1f046697f0695e75e874f8572dbef.png](https://img3.qq.tc/2022/06/28/6e1f046697f0695e75e874f8572dbef.png)

**Comment by clarkwinkelmann** [comment] 2022-07-03 20:52
Sorry for the late reply.

I was able to replicate the issue, I will try to get this fixed in the coming week.

The problem is with Flarum's gate priority, the Tags extension is overriding this extension's gate output because DENY has priority over ALLOW even though allow was returned for the exact ability name while DENY was returned for the general `can`. I'll probably have to switch it to a FORCE_ALLOW.

Output from the gate logger extension for a discussion that matches this issue description:

```
[2022-07-03 20:39:41] flarum.DEBUG: Gate Logger seeTaxonomy(Actor: User, Flarum\Discussion\Discussion: 6)
Flarum\Discussion\Access\DiscussionPolicy@can: [NULL]
Flarum\Tags\Access\DiscussionPolicy@can: DENY
Flamarkt\Taxonomies\Access\DiscussionPolicy@seeTaxonomy: [TRUE] => ALLOW
Decision: DENY (Criteria Priority: DENY)
```

**Closed as completed** 2022-09-07 13:55 UTC
